Update PCA and EFA to include JASP output of rotated factor solutions…
jasp-stats/jasp-verification-project pull request #8
Opened 2022-04-06 00:56 UTC by JTPetter

… and remark about differences

2022-04-06 14:01 UTC, juliuspfadt requested changes
Looks good. I am just wondering why there are not multiple figures in the PCA results for JASP as there are for the EFA? It could be two figures, one with factor loadings an factor characteristics and one for the scree plot? This way, the loadings would not be cut-off.

2022-04-06 14:01 UTC, juliuspfadt commented on 07_Factor.Rmd
> +The rotation used was "Varimax". The differences in the results of the rotated factor solutions between the software are due to different optimization methods used.
I would say 
```
The rotation used was "Varimax". The differences in the results of the rotated factor solutions between the software are due to differences in the optimization methods used. 
```
Because they are not really using different methods but within these methods the stopping value is sometimes different, or the starting point is different and they find different minima/maxima.

2022-04-06 14:01 UTC, juliuspfadt commented on 07_Factor.Rmd
> +The method used was "Principal Axis Factoring" and the rotation used was "Varimax". The differences in the results of the rotated factor solutions between the software are due to different optimizati
Same here
```
The rotation used was "Varimax". The differences in the results of the rotated factor solutions between the software are due to differences in the optimization methods used.
```

2022-04-07 01:04 UTC, JTPetter commented
Okay, I have addressed your comments, thanks! @juliuspf

2022-04-07 12:49 UTC, juliuspf approved these changes

2022-04-07 23:45 UTC, JTPetter commented
@AlexanderLyNL could you approve this, please? Needs to be done by someone with write access to this repo :)

2022-04-08 07:16 UTC, AlexanderLyNL approved these changes

2022-04-08 07:38 UTC, AlexanderLyNL commented
I pressed squash and merge, but it's waiting for succesful checks. At the same time I see that this has not been deployed. Is that what it's supposed to do?

2022-04-08 12:02 UTC, juliuspf commented
hmm. can you try again? not sure why it is not working, you should have the most access out of all of us :)

2022-04-08 20:17 UTC, merged

2022-04-08 20:18 UTC, AlexanderLyNL commented
I disabled the "wait until checks are done", but it's kinda weird that my github expects checks.